tenantId: tenant3
organizationName: "Arnold Simulation Corp"
agentConfig:
  mode: "idle"
  targetCategory: "none"

service:
  type: ClusterIP   # required to fix the nil pointer error
  port: 80

httpRoute:
  enabled: false

ingress:
  enabled: false
